# Generated by Django 3.0.4 on 2020-04-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnr_app', '0002_friendrequest_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='First Name'),
        ),
    ]
