# Generated by Django 3.0.4 on 2020-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnr_app', '0004_auto_20200409_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=250, null=True, verbose_name='username'),
        ),
    ]
