# Generated by Django 3.0.4 on 2020-04-15 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnr_app', '0008_auto_20200414_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSwipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one_id', models.IntegerField()),
                ('user_two_id', models.IntegerField()),
                ('restaurant_list', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('good_list', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None), size=None)),
                ('bad_list', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None), size=None)),
            ],
        ),
    ]
