# Generated by Django 3.0.4 on 2020-04-15 19:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnr_app', '0011_auto_20200415_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
