# Generated by Django 3.0.4 on 2020-04-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnr_app', '0012_auto_20200415_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='all_resteraunts',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
